### ISSUE TITLE
Getting this error while signup

### ISSUE THREAD

**Issue by cloudtestsoftware** [toanhtran/foodtasker#1]
Hi,

I was trying with your app, but getting below error. Looks like there is no table. Can you tell me how can I create the database tables?

Request Method: | POST
-- | --
http://127.0.0.1:8000/restaurant/sign-up
1.10
OperationalError
no such table: auth_user
/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py in execute, line 337
/usr/bin/python
2.7.12
['/home/srimanta/git/fooddelivery/foodtasker-master',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages/PILcompat',  '/usr/lib/python2.7/dist-packages/gtk-2.0',  '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']
Thu, 22 Mar 2018 22:44:38 +0000

**Comment by PEDROMHB** [comment]
you made the migrations? python manage.py makemigrations and python manage.py migrate
be sure to also create a superuser.
recuerde que para este proyecto debe usar python 3.5.2 y django 1.10.
If the error continues create a new virtualenv and a new database.

**Comment by toanhtran** [comment]
Make sure you create the tables in your db based on the migration files created and create a superuser like @PEDROMHB mentioned. 

$ python manage.py makemigrations (creates migration files based on your models)
$ python manage.py migrate  (creates the tables in your db based on the migration files)
$ python manage.py createsuperuser (creates a superuser for your application in the db)
$ python manage.py runserver ( run server)


Then you can view your admin dashboard with this link
http://127.0.0.1:8000/admin/
